const age = 13;
console.log(age);
const name = "pavlo";
console.log(name);
const isStudent = true;
console.log(isStudent);
const myString = "keep the infants from the wall. author: Odysseus";
console.log(myString);
const myNumber = 5 + 10;
console.log(myNumber);
const myNull = null;
console.log(myNull);
const userName = prompt("enter name");
alert(userName);
console.log(typeof userName);
const myAnswer = confirm("do you want to leave the page?");
console.log(myAnswer);
alert("dangerous");
confirm("continue?");